repos:
- repo: local
  hooks:
  - id: tests
    name: run tests
    entry: pytest tests
    language: python
    types: [python]
    stages: [commit]
  - id: ruff
    name: ruff
    entry: ruff check .
    language: python
    types: [python]
    stages: [commit]
